serviceConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 12345
  path: /api/g

loggerConfig:
  outputDir: ./logs/
  outputFile: gateway.log

databaseConfig:
  dbUsername: cs122bg10
  dbPassword: YFzC5R0NvAj7~
  dbHostname: localhost
  dbPort: 3310
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: cs122bg10
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST

threadConfig:
  numThreads: 10
  requestDelay: 5

idmConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 2845
  path: /api/idm

idmEndpoints:
  register: /register
  login: /login
  session: /session
  privilege: /privilege

moviesConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 2846
  path: /api/movies

moviesEndpoints:
  search: /search
  browse: /browse/
  get: /get/
  thumbnail: /thumbnail
  people: /people
  peopleSearch: /people/search
  peopleGet: /people/get/

billingConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 2847
  path: /api/billing

billingEndpoints:
  cartInsert: /cart/insert
  cartUpdate: /cart/update
  cartDelete: /cart/delete
  cartRetrieve: /cart/retrieve
  cartClear: /cart/clear
  orderPlace: /order/place
  orderRetrieve: /order/retrieve
  orderComplete: /order/complete
